import {
  PrismaClient,
  UserRole,
  Gender,
  EducationLevel,
  GraduatedFrom,
  Country,
  LanguageLevel,
  TripType,
  TripStatus,
  LaoProvince,
} from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...\n');

  const adminHash = await bcrypt.hash('Admin@1234', 10);
  const empHash = await bcrypt.hash('Employee@1234', 10);

  // ────────────────────────────────────────────────────────────────────────────
  // Admin
  // ────────────────────────────────────────────────────────────────────────────
  const admin = await prisma.user.upsert({
    where: { username: 'admin' },
    update: {},
    create: {
      email: 'admin@arist.com',
      username: 'admin',
      password: adminHash,
      role: UserRole.ADMIN,
      firstName: 'System',
      lastName: 'Admin',
      isActive: true,
      mustChangePassword: false,
    },
  });
  console.log('  ✓ admin:', admin.username);

  // ────────────────────────────────────────────────────────────────────────────
  // Departments
  // ────────────────────────────────────────────────────────────────────────────
  const deptDefs = [
    'ເທັກໂນໂລຊີ',
    'ຊັບພະຍາກອນມະນຸດ',
    'ການເງິນ',
    'ການດຳເນີນງານ',
    'ການຕະຫຼາດ',
    'ຜູ້ບໍລິຫານ',
  ];

  const [itDept, hrDept, financeDept, opsDept, marketingDept, mgmtDept] =
    await Promise.all(
      deptDefs.map((name) =>
        prisma.department.upsert({
          where: { name },
          update: {},
          create: { name, isActive: true },
        }),
      ),
    );
  console.log(`  ✓ ${deptDefs.length} departments`);

  // ────────────────────────────────────────────────────────────────────────────
  // Positions
  // ────────────────────────────────────────────────────────────────────────────
  const posDefs = [
    'ຜູ້ອຳນວຍການ',
    'ຜູ້ຈັດການ',
    'ນັກພັດທະນາ Senior',
    'ນັກພັດທະນາ',
    'ໜ້າທີ່ HR',
    'ນັກບັນຊີ',
    'ໜ້າທີ່ການຕະຫຼາດ',
    'ໜ້າທີ່ການດຳເນີນງານ',
    'ຜູ້ດູແລລະບົບ',
    'ນັກວິເຄາະຂໍ້ມູນ',
  ];

  const [
    directorPos,
    managerPos,
    srDevPos,
    devPos,
    hrOffPos,
    accountantPos,
    mktOffPos,
    opsOffPos,
    sysAdminPos,
    dataAnalystPos,
  ] = await Promise.all(
    posDefs.map((name) =>
      prisma.position.upsert({
        where: { name },
        update: {},
        create: { name, isActive: true },
      }),
    ),
  );
  console.log(`  ✓ ${posDefs.length} positions`);

  // ────────────────────────────────────────────────────────────────────────────
  // Employees  (password: Employee@1234)
  // ────────────────────────────────────────────────────────────────────────────
  const empDefs = [
    // ── IT ────────────────────────────────────────────────────────────────────
    {
      username: 'somchit',
      email: 'somchit@arist.com',
      firstName: 'ສົມຈິດ',
      lastName: 'ວົງສະຫວັນ',
      gender: Gender.MALE,
      deptId: itDept.id,
      posId: srDevPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ວິທະຍາສາດຄອມພິວເຕີ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.ADVANCED,
      viet: LanguageLevel.BASIC,
      chinese: LanguageLevel.NONE,
      other: 'ພາສາໄທ (ພື້ນຖານ)',
      passportExpiry: new Date('2027-06-15'),
    },
    {
      username: 'anousonh',
      email: 'anousonh@arist.com',
      firstName: 'ອານຸສອນ',
      lastName: 'ສີວົງ',
      gender: Gender.MALE,
      deptId: itDept.id,
      posId: devPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ເທັກໂນໂລຊີຂໍ້ມູນ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.INTERMEDIATE,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'soukjai',
      email: 'soukjai@arist.com',
      firstName: 'ສຸກໃຈ',
      lastName: 'ດວງດີ',
      gender: Gender.MALE,
      deptId: itDept.id,
      posId: devPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລສຸພານຸວົງ',
      field: 'ວິທະຍາສາດຄອມພິວເຕີ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.INTERMEDIATE,
      viet: LanguageLevel.BASIC,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'khamhieng',
      email: 'khamhieng@arist.com',
      firstName: 'ຄຳຮ່ຽງ',
      lastName: 'ຕາສາລີ',
      gender: Gender.MALE,
      deptId: itDept.id,
      posId: sysAdminPos.id,
      edu: EducationLevel.DIPLOMA,
      institution: 'ໂຮງຮຽນອາຊີວະ ນະຄອນຫຼວງ',
      field: 'ເທັກໂນໂລຊີຄອມພິວເຕີ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.BASIC,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'namphonh',
      email: 'namphonh@arist.com',
      firstName: 'ນ້ຳຝົນ',
      lastName: 'ໂພທິລັດ',
      gender: Gender.MALE,
      deptId: itDept.id,
      posId: dataAnalystPos.id,
      edu: EducationLevel.MASTER,
      institution: 'Asian Institute of Technology (AIT)',
      field: 'ວິທະຍາສາດຂໍ້ມູນ ແລະ ປັນຍາປະດິດ',
      gradFrom: GraduatedFrom.ABROAD,
      gradCountry: Country.THAILAND,
      eng: LanguageLevel.ADVANCED,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.BASIC,
      other: 'ພາສາໄທ (ຄ່ອງ)',
      passportExpiry: new Date('2028-03-20'),
    },
    {
      username: 'xaiyha',
      email: 'xaiyha@arist.com',
      firstName: 'ໄຊຍະ',
      lastName: 'ດາລາ',
      gender: Gender.MALE,
      deptId: itDept.id,
      posId: devPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ເທັກໂນໂລຊີຂໍ້ມູນ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.BASIC,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    // ── HR ────────────────────────────────────────────────────────────────────
    {
      username: 'vilai',
      email: 'vilai@arist.com',
      firstName: 'ວິໄລ',
      lastName: 'ບຸນມີ',
      gender: Gender.FEMALE,
      deptId: hrDept.id,
      posId: managerPos.id,
      edu: EducationLevel.MASTER,
      institution: 'ມະຫາວິທະຍາໄລຮ່ານອ',
      field: 'ການຈັດການຊັບພະຍາກອນມະນຸດ',
      gradFrom: GraduatedFrom.ABROAD,
      gradCountry: Country.VIETNAM,
      eng: LanguageLevel.ADVANCED,
      viet: LanguageLevel.ADVANCED,
      chinese: LanguageLevel.NONE,
      other: 'ພາສາຫວຽດນາມ (ຄ່ອງ)',
      passportExpiry: new Date('2026-11-10'),
    },
    {
      username: 'amphon',
      email: 'amphon@arist.com',
      firstName: 'ອຳພອນ',
      lastName: 'ທ່ອງທາ',
      gender: Gender.FEMALE,
      deptId: hrDept.id,
      posId: hrOffPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ການຈັດການທຸລະກິດ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.INTERMEDIATE,
      viet: LanguageLevel.BASIC,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'fai',
      email: 'fai@arist.com',
      firstName: 'ໄຟ',
      lastName: 'ບຸນໂຮງ',
      gender: Gender.FEMALE,
      deptId: hrDept.id,
      posId: hrOffPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລສຸພານຸວົງ',
      field: 'ຊັບພະຍາກອນມະນຸດ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.BASIC,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'pong',
      email: 'pong@arist.com',
      firstName: 'ປ້ອງ',
      lastName: 'ຈັນດາລາ',
      gender: Gender.FEMALE,
      deptId: hrDept.id,
      posId: hrOffPos.id,
      edu: EducationLevel.DIPLOMA,
      institution: 'ວິທະຍາໄລ ນະຄອນຫຼວງວຽງຈັນ',
      field: 'ການຈັດການ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.NONE,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    // ── Finance ───────────────────────────────────────────────────────────────
    {
      username: 'bounthong',
      email: 'bounthong@arist.com',
      firstName: 'ບຸນທ້ວງ',
      lastName: 'ແສງຄຳ',
      gender: Gender.MALE,
      deptId: financeDept.id,
      posId: managerPos.id,
      edu: EducationLevel.MASTER,
      institution: 'ມະຫາວິທະຍາໄລ Thammasat',
      field: 'ການເງິນ ແລະ ການລົງທຶນ',
      gradFrom: GraduatedFrom.ABROAD,
      gradCountry: Country.THAILAND,
      eng: LanguageLevel.INTERMEDIATE,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.BASIC,
      other: 'ພາສາໄທ (ຄ່ອງ)',
      passportExpiry: new Date('2027-08-01'),
    },
    {
      username: 'dawsoud',
      email: 'dawsoud@arist.com',
      firstName: 'ດາວສຸດ',
      lastName: 'ນ້ຳທິບ',
      gender: Gender.MALE,
      deptId: financeDept.id,
      posId: accountantPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ວິທະຍາໄລດ້ານການເງິນ ແລະ ການທະນາຄານ',
      field: 'ການບັນຊີ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.BASIC,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'sor',
      email: 'sor@arist.com',
      firstName: 'ສໍ່',
      lastName: 'ເພັດສາຍ',
      gender: Gender.FEMALE,
      deptId: financeDept.id,
      posId: accountantPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ການບັນຊີ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.INTERMEDIATE,
      viet: LanguageLevel.BASIC,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'kanh',
      email: 'kanh@arist.com',
      firstName: 'ກ້ານ',
      lastName: 'ມ່ວງດີ',
      gender: Gender.FEMALE,
      deptId: financeDept.id,
      posId: accountantPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ການບັນຊີ ແລະ ການເງິນ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.BASIC,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    // ── Operations ────────────────────────────────────────────────────────────
    {
      username: 'souksaikhe',
      email: 'souksaikhe@arist.com',
      firstName: 'ສຸກສາໄຂ',
      lastName: 'ຄຳສຸກ',
      gender: Gender.FEMALE,
      deptId: opsDept.id,
      posId: managerPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ການຈັດການດ້ານການດຳເນີນງານ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.ADVANCED,
      viet: LanguageLevel.INTERMEDIATE,
      chinese: LanguageLevel.NONE,
      other: 'ພາສາໄທ (ຄ່ອງ)',
      passportExpiry: new Date('2026-09-30'),
    },
    {
      username: 'khamluan',
      email: 'khamluan@arist.com',
      firstName: 'ຄຳລ້ວນ',
      lastName: 'ໂພທິສານ',
      gender: Gender.FEMALE,
      deptId: opsDept.id,
      posId: opsOffPos.id,
      edu: EducationLevel.DIPLOMA,
      institution: 'ໂຮງຮຽນອາຊີວະ ນະຄອນຫຼວງ',
      field: 'ການຈັດການ ແລະ ການບໍລິຫານ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.BASIC,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'somphone',
      email: 'somphone@arist.com',
      firstName: 'ສົມພອນ',
      lastName: 'ຄຳມ່ວນ',
      gender: Gender.MALE,
      deptId: opsDept.id,
      posId: opsOffPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລສຸພານຸວົງ',
      field: 'ການຈັດການທຸລະກິດ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.INTERMEDIATE,
      viet: LanguageLevel.BASIC,
      chinese: LanguageLevel.NONE,
    },
    // ── Marketing ─────────────────────────────────────────────────────────────
    {
      username: 'chantala',
      email: 'chantala@arist.com',
      firstName: 'ຈັນທະລາ',
      lastName: 'ຫຼ້າ',
      gender: Gender.FEMALE,
      deptId: marketingDept.id,
      posId: managerPos.id,
      edu: EducationLevel.MASTER,
      institution: 'ມະຫາວິທະຍາໄລຈຸລາລົງກອນ',
      field: 'ການຕະຫຼາດ ແລະ ການສື່ສານ',
      gradFrom: GraduatedFrom.ABROAD,
      gradCountry: Country.THAILAND,
      eng: LanguageLevel.ADVANCED,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.BASIC,
      other: 'ພາສາໄທ (ຄ່ອງ)',
      passportExpiry: new Date('2028-01-15'),
    },
    {
      username: 'fa',
      email: 'fa@arist.com',
      firstName: 'ຟ້າ',
      lastName: 'ເດດດວງ',
      gender: Gender.MALE,
      deptId: marketingDept.id,
      posId: mktOffPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລແຫ່ງຊາດ',
      field: 'ການຕະຫຼາດ ແລະ ການໂຄສະນາ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.INTERMEDIATE,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.NONE,
    },
    {
      username: 'vongduang',
      email: 'vongduang@arist.com',
      firstName: 'ວົງດວງ',
      lastName: 'ສິດທິເດດ',
      gender: Gender.FEMALE,
      deptId: marketingDept.id,
      posId: mktOffPos.id,
      edu: EducationLevel.BACHELOR,
      institution: 'ມະຫາວິທະຍາໄລສຸພານຸວົງ',
      field: 'ການຕະຫຼາດ',
      gradFrom: GraduatedFrom.DOMESTIC,
      gradCountry: Country.LAOS,
      eng: LanguageLevel.BASIC,
      viet: LanguageLevel.BASIC,
      chinese: LanguageLevel.NONE,
    },
    // ── Management ────────────────────────────────────────────────────────────
    {
      username: 'somxai',
      email: 'somxai@arist.com',
      firstName: 'ສົມຊາຍ',
      lastName: 'ຂຽວດວງ',
      gender: Gender.MALE,
      deptId: mgmtDept.id,
      posId: directorPos.id,
      edu: EducationLevel.PHD,
      institution: 'Université Jean Moulin Lyon 3',
      field: 'ການຈັດການວິສາຫະກິດ',
      gradFrom: GraduatedFrom.ABROAD,
      gradCountry: Country.FRANCE,
      eng: LanguageLevel.NATIVE,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.INTERMEDIATE,
      other: 'ພາສາຝຣັ່ງ (ຄ່ອງ), ໄທ (ພື້ນຖານ)',
      passportExpiry: new Date('2029-04-22'),
    },
    {
      username: 'phoxai',
      email: 'phoxai@arist.com',
      firstName: 'ໂພໄຊ',
      lastName: 'ວົງສ໌',
      gender: Gender.MALE,
      deptId: mgmtDept.id,
      posId: managerPos.id,
      edu: EducationLevel.MASTER,
      institution: 'ມະຫາວິທະຍາໄລປັກກິ່ງ',
      field: 'ການບໍລິຫານທຸລະກິດ (MBA)',
      gradFrom: GraduatedFrom.ABROAD,
      gradCountry: Country.CHINA,
      eng: LanguageLevel.ADVANCED,
      viet: LanguageLevel.NONE,
      chinese: LanguageLevel.ADVANCED,
      other: 'ພາສາຈີນ (ຄ່ອງ)',
      passportExpiry: new Date('2027-12-05'),
    },
  ];

  const employees = await Promise.all(
    empDefs.map((e) =>
      prisma.user.upsert({
        where: { username: e.username },
        update: {
          institutionName: e.institution,
          fieldOfStudy: e.field,
          graduatedFrom: e.gradFrom,
          graduatedCountry: e.gradCountry,
          vietnameseLevel: e.viet,
          chineseLevel: e.chinese,
          otherLanguages: e.other ?? null,
        },
        create: {
          email: e.email,
          username: e.username,
          password: empHash,
          role: UserRole.EMPLOYEE,
          firstName: e.firstName,
          lastName: e.lastName,
          gender: e.gender,
          isActive: true,
          mustChangePassword: false,
          departmentId: e.deptId,
          positionId: e.posId,
          educationLevel: e.edu,
          institutionName: e.institution,
          fieldOfStudy: e.field,
          graduatedFrom: e.gradFrom,
          graduatedCountry: e.gradCountry,
          englishLevel: e.eng,
          vietnameseLevel: e.viet,
          chineseLevel: e.chinese,
          otherLanguages: e.other ?? null,
          passportExpiry: e.passportExpiry ?? null,
        },
      }),
    ),
  );
  console.log(`  ✓ ${employees.length} employees`);

  const emp = Object.fromEntries(employees.map((e) => [e.username, e]));

  // ────────────────────────────────────────────────────────────────────────────
  // Business Trips  (delete & recreate for idempotency)
  // ────────────────────────────────────────────────────────────────────────────
  await prisma.businessTrip.deleteMany({});

  const tripDefs: {
    title: string;
    tripType: TripType;
    destinationProvince?: LaoProvince;
    destinationCountry?: Country;
    departureDate: string;
    returnDate: string;
    status: TripStatus;
    userId: string;
    submittedAt?: Date;
    verifiedById?: string;
    verifiedAt?: Date;
    rejectionReason?: string;
  }[] = [
    // ── VERIFIED  International ───────────────────────────────────────────────
    {
      title: 'ການປະຊຸມ IT ນາໆຊາດ ປີ 2025',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.THAILAND,
      departureDate: '2025-03-10',
      returnDate: '2025-03-15',
      status: TripStatus.VERIFIED,
      userId: emp['somchit'].id,
      submittedAt: new Date('2025-03-04'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-03-05'),
    },
    {
      title: 'ການຝຶກອົບຮົມ AI ທີ່ສິງກະໂປ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.SINGAPORE,
      departureDate: '2025-04-20',
      returnDate: '2025-04-25',
      status: TripStatus.VERIFIED,
      userId: emp['namphonh'].id,
      submittedAt: new Date('2025-04-14'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-04-15'),
    },
    {
      title: 'ການປະຊຸມ HR ອາຊຽນ ຮ່ານອ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.VIETNAM,
      departureDate: '2025-05-08',
      returnDate: '2025-05-12',
      status: TripStatus.VERIFIED,
      userId: emp['vilai'].id,
      submittedAt: new Date('2025-04-30'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-05-01'),
    },
    {
      title: 'ງານ Marketing Summit ກວາງໂຈວ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.CHINA,
      departureDate: '2025-06-15',
      returnDate: '2025-06-20',
      status: TripStatus.VERIFIED,
      userId: emp['chantala'].id,
      submittedAt: new Date('2025-06-09'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-06-10'),
    },
    {
      title: 'ການຝຶກ Finance ກຣຸງເທບ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.THAILAND,
      departureDate: '2025-07-01',
      returnDate: '2025-07-05',
      status: TripStatus.VERIFIED,
      userId: emp['bounthong'].id,
      submittedAt: new Date('2025-06-24'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-06-25'),
    },
    // ── VERIFIED  Domestic ────────────────────────────────────────────────────
    {
      title: 'ກວດກາໂຄງການ ແຂວງສາວັນນະເຂດ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.SAVANNAKHET,
      departureDate: '2025-08-10',
      returnDate: '2025-08-13',
      status: TripStatus.VERIFIED,
      userId: emp['somxai'].id,
      submittedAt: new Date('2025-08-04'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-08-05'),
    },
    {
      title: 'ຝຶກງານ ແຂວງຫຼວງພະບາງ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.LUANG_PRABANG,
      departureDate: '2025-09-05',
      returnDate: '2025-09-08',
      status: TripStatus.VERIFIED,
      userId: emp['souksaikhe'].id,
      submittedAt: new Date('2025-08-31'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-09-01'),
    },
    {
      title: 'ກວດກາສາຂາ ແຂວງຈຳປາສັກ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.CHAMPASAK,
      departureDate: '2025-10-12',
      returnDate: '2025-10-15',
      status: TripStatus.VERIFIED,
      userId: emp['phoxai'].id,
      submittedAt: new Date('2025-10-07'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-10-08'),
    },
    {
      title: 'ກວດກາໂຄງການ ແຂວງຊຽງຂວາງ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.XIANGKHOUANG,
      departureDate: '2025-11-03',
      returnDate: '2025-11-06',
      status: TripStatus.VERIFIED,
      userId: emp['somphone'].id,
      submittedAt: new Date('2025-10-27'),
      verifiedById: admin.id,
      verifiedAt: new Date('2025-10-28'),
    },
    // ── PENDING  International ────────────────────────────────────────────────
    {
      title: 'ການປະຊຸມ DevOps ໂຕກ່ຽວ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.JAPAN,
      departureDate: '2026-02-10',
      returnDate: '2026-02-15',
      status: TripStatus.PENDING,
      userId: emp['anousonh'].id,
      submittedAt: new Date('2026-01-15'),
    },
    {
      title: 'ງານ Fintech Forum ກວາງໂຈວ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.CHINA,
      departureDate: '2026-02-20',
      returnDate: '2026-02-25',
      status: TripStatus.PENDING,
      userId: emp['dawsoud'].id,
      submittedAt: new Date('2026-01-20'),
    },
    {
      title: 'ການຝຶກ Marketing Digital ກຣຸງເທບ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.THAILAND,
      departureDate: '2026-03-15',
      returnDate: '2026-03-20',
      status: TripStatus.PENDING,
      userId: emp['fa'].id,
      submittedAt: new Date('2026-02-20'),
    },
    {
      title: 'ການຝຶກ HR Systems ຮ່ານອ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.VIETNAM,
      departureDate: '2026-04-01',
      returnDate: '2026-04-05',
      status: TripStatus.PENDING,
      userId: emp['amphon'].id,
      submittedAt: new Date('2026-03-01'),
    },
    // ── PENDING  Domestic ─────────────────────────────────────────────────────
    {
      title: 'ກວດກາ IT Infrastructure ຫຼວງພະບາງ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.LUANG_PRABANG,
      departureDate: '2026-03-05',
      returnDate: '2026-03-07',
      status: TripStatus.PENDING,
      userId: emp['khamhieng'].id,
      submittedAt: new Date('2026-02-10'),
    },
    {
      title: 'ກວດກາສາຂາ ສາລາວັນ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.SALAVAN,
      departureDate: '2026-04-10',
      returnDate: '2026-04-12',
      status: TripStatus.PENDING,
      userId: emp['khamluan'].id,
      submittedAt: new Date('2026-03-15'),
    },
    // ── REJECTED ──────────────────────────────────────────────────────────────
    {
      title: 'ການປະຊຸມ AI ຊຽງໃໝ່',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.THAILAND,
      departureDate: '2025-12-01',
      returnDate: '2025-12-05',
      status: TripStatus.REJECTED,
      userId: emp['soukjai'].id,
      submittedAt: new Date('2025-11-18'),
      rejectionReason: 'ງົບປະມານໄລຍະນີ້ບໍ່ພຽງພໍ',
      verifiedById: admin.id,
      verifiedAt: new Date('2025-11-20'),
    },
    {
      title: 'ການຝຶກ Accounting ໂຊລ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.SOUTH_KOREA,
      departureDate: '2026-01-15',
      returnDate: '2026-01-20',
      status: TripStatus.REJECTED,
      userId: emp['sor'].id,
      submittedAt: new Date('2026-01-03'),
      rejectionReason: 'ຕ້ອງສົ່ງເອກະສານສະໜັບສະໜຸນເພີ່ມ',
      verifiedById: admin.id,
      verifiedAt: new Date('2026-01-05'),
    },
    {
      title: 'ງານ Marketing Expo ກົວລາລຳເປີ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.MALAYSIA,
      departureDate: '2026-02-01',
      returnDate: '2026-02-07',
      status: TripStatus.REJECTED,
      userId: emp['vongduang'].id,
      submittedAt: new Date('2026-01-23'),
      rejectionReason: 'ໄລຍະເວລາຊ້ອນກັນກັບໂຄງການພາຍໃນ',
      verifiedById: admin.id,
      verifiedAt: new Date('2026-01-25'),
    },
    // ── DRAFT ─────────────────────────────────────────────────────────────────
    {
      title: 'ການຝຶກ Cloud Computing ສິງກະໂປ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.SINGAPORE,
      departureDate: '2026-05-10',
      returnDate: '2026-05-15',
      status: TripStatus.DRAFT,
      userId: emp['xaiyha'].id,
    },
    {
      title: 'ກວດກາລູກຄ້າ ສາວັນນະເຂດ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.SAVANNAKHET,
      departureDate: '2026-05-20',
      returnDate: '2026-05-22',
      status: TripStatus.DRAFT,
      userId: emp['somphone'].id,
    },
    {
      title: 'ການຝຶກ Leadership ກຣຸງເທບ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.THAILAND,
      departureDate: '2026-06-01',
      returnDate: '2026-06-05',
      status: TripStatus.DRAFT,
      userId: emp['phoxai'].id,
    },
    {
      title: 'ງານ Startup Weekend ຮ່ານອ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.VIETNAM,
      departureDate: '2026-06-10',
      returnDate: '2026-06-14',
      status: TripStatus.DRAFT,
      userId: emp['namphonh'].id,
    },
    {
      title: 'ກວດກາສາຂາ ຫຼວງນ້ຳທາ',
      tripType: TripType.DOMESTIC,
      destinationProvince: LaoProvince.LUANG_NAMTHA,
      departureDate: '2026-06-20',
      returnDate: '2026-06-23',
      status: TripStatus.DRAFT,
      userId: emp['kanh'].id,
    },
    {
      title: 'ການຝຶກ Data Analysis ໂຕກ່ຽວ',
      tripType: TripType.INTERNATIONAL,
      destinationCountry: Country.JAPAN,
      departureDate: '2026-07-05',
      returnDate: '2026-07-10',
      status: TripStatus.DRAFT,
      userId: emp['somchit'].id,
    },
  ];

  await prisma.businessTrip.createMany({
    data: tripDefs.map((t) => ({
      title: t.title,
      tripType: t.tripType,
      destinationProvince: t.destinationProvince ?? null,
      destinationCountry: t.destinationCountry ?? null,
      departureDate: new Date(t.departureDate),
      returnDate: new Date(t.returnDate),
      status: t.status,
      userId: t.userId,
      submittedAt: t.submittedAt ?? null,
      verifiedById: t.verifiedById ?? null,
      verifiedAt: t.verifiedAt ?? null,
      rejectionReason: t.rejectionReason ?? null,
    })),
  });
  console.log(`  ✓ ${tripDefs.length} business trips`);

  console.log('\n✅ Seed complete!');
  console.log('\nCredentials:');
  console.log('  admin    → Admin@1234');
  console.log('  employee → Employee@1234  (e.g. somchit, vilai, chantala …)');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
